
from tkinter import *
from tkinter import ttk
from tkinter import messagebox
from tkinter.font import BOLD
from controladores.logicaEntradas import logicaEntradas

class entradas:
    def __init__(self,ventana):
        #instancia del controlador logica Entradas
        self.entries=logicaEntradas()
        self.ventana=ventana
        self.ventana.title("Entradas")
        self.ventana.geometry("1030x555")
        self.ventana.config(bg="slategrey")
        self.ventana.resizable(0,0)
        self.ventana.iconbitmap("imagenes/Entradas.ico")
        self.frame=LabelFrame(self.ventana, text="Entradas", font=('Times', 10,BOLD),padx=20,pady=20)
        self.frame.config(labelanchor=N,width=500)
        self.frame.grid(row=0,column=0,columnspan=3)
        Label(self.frame,text="Por favor escribir el codigo del producto para poder buscarlo",font=('Times', 10)).grid(row=0,columnspan=2,pady=5,sticky=W+E)
        Button(self.frame,text="Buscar",font=('Times', 10,BOLD),command=lambda: self.entries.buscarEntrada(self.arbol,self.entrada1.get())).grid(row=1,column=0)
        self.entrada1=Entry(self.frame,width=50)
        self.entrada1.grid(row=1,column=1)
        Button(self.frame,text="Añadir una entrada", font=('Times', 10,BOLD), command=self.añadirentrada).grid(row=2,columnspan=2,pady=5,sticky=W+E)
        Button(self.frame,text="Eliminar una entrada", font=('Times', 10,BOLD),command=lambda: self.entries.eliminarEntrada(self.arbol,self.arbol.item(self.arbol.selection())["text"])).grid(row=3,columnspan=2,pady=5,sticky=W+E)
        Button(self.frame,text="Editar una entrada", font=('Times', 10,BOLD), command=self.editarentrada).grid(row=4,columnspan=2,pady=5,sticky=W+E)
        Button(self.frame,text="Refrescar", font=('Times', 10,BOLD),command=lambda: self.entries.llenarEntradas(self.arbol)).grid(row=5,columnspan=2,pady=5,sticky=W+E)
        Button(self.frame,text="Exportar entradas a un excel", font=('Times', 10,BOLD),command=self.pantallita1).grid(row=6,columnspan=2,pady=5,sticky=W+E)
        #lambda:self.entries.exportarEntradas("SELECT * FROM entradas",self.arbol)
        self.arbol=ttk.Treeview(self.ventana,columns=('#1','#2','#3','#4'))
        self.arbol.grid(row=5,column=0,columnspan=2,padx=2)
        self.arbol.heading("#0",text="id_entradas",anchor = CENTER)
        self.arbol.heading("#1",text="Codigo",anchor = CENTER)
        self.arbol.heading("#2",text="Nombre",anchor = CENTER)
        self.arbol.heading("#3",text="Entradas",anchor=CENTER)
        self.arbol.heading("#4",text="Fecha_entradas",anchor = CENTER)
        scroll=Scrollbar(self.ventana,command=self.arbol.yview)
        scroll.grid(row=5,column=2,sticky="nsew")
        Button(self.ventana,text="Salir de la vista de entradas", font=('Times', 10,BOLD),command=self.ventana.destroy).grid(row=9,column=0,columnspan=2,sticky=W+E)
        self.entries.llenarEntradas(self.arbol)
        self.ventana.mainloop()

    
    def pantallita1(self):
      #Vista para poner nombre a listas
      self.pantallita1=Toplevel(self.ventana)
      self.pantallita1.geometry("300x200")
      self.pantallita1.title("Titulo de listas")
      self.pantallita1.config(bg="slategrey")
      self.pantallita1.resizable(0,0)
      self.pantallita1.iconbitmap("imagenes/escritura.ico")
      Label(self.pantallita1, text= "Por favor escribir un titulo", font=('Times', 10), bg="slategrey",fg="gray1").pack()
      Label(self.pantallita1, text= "para la lista", font=('Times', 10), bg="slategrey",fg="gray1").pack()
      Label(self.pantallita1, text= " ", bg="slategrey").pack()
      nombreEntradas=Entry(self.pantallita1, width=40)
      nombreEntradas.pack()
      Label(self.pantallita1, text= " ", bg="slategrey").pack()
      Button(self.pantallita1, text="Confirmar", font=('Times', 10), fg="gray1", command=lambda:self.entries.exportarEntradas("SELECT * FROM entradas",self.arbol,nombreEntradas.get())).pack()
      Label(self.pantallita1, text= " ", bg="slategrey").pack()
      Button(self.pantallita1, text="Cancelar", font=('Times', 10), fg="gray1", command=self.pantallita1.destroy).pack()

    def añadirentrada(self):
      #Vista de la ventana añadir entrada
      self.añadirentrada=Toplevel(self.ventana)
      self.añadirentrada.geometry("400x355")
      self.añadirentrada.title("Añadir Entrada")
      self.añadirentrada.config(bg="slategrey")
      self.añadirentrada.resizable(0,0)
      self.añadirentrada.iconbitmap("imagenes/Entradas.ico")
      Label(self.añadirentrada ,text="", bg = "slateGray").pack()
      Label(self.añadirentrada ,text="Por favor llenar las siguientes casillas para",font=('Times',10,), fg="black", bg = "slateGray").pack()
      Label(self.añadirentrada ,text="añadir una nueva entrada", font=('Times',10,), fg="black", bg = "slateGray").pack()
      Label(self.añadirentrada ,text="", bg = "slateGray").pack()
      Label(self.añadirentrada ,text="Codigo", font=('Times',10,), fg="black", width = "12", height = "1", bg = "slateGray").pack()
      C_entry = Entry(self.añadirentrada, width = "40")
      C_entry.pack()
      Label(self.añadirentrada ,text="", bg = "slateGray").pack()
      Label(self.añadirentrada ,text="Nombre", font=('Times',10,), fg="black", width = "12", height = "1", bg = "slateGray").pack()
      N_entry = Entry(self.añadirentrada, width = "40")
      N_entry.pack()
      Label(self.añadirentrada ,text="", bg = "slateGray").pack()
      Label(self.añadirentrada ,text="Entradas", font=('Times',10,), fg="black", width = "12", height = "1", bg = "slateGray").pack()
      E_entry = Entry(self.añadirentrada, width = "40")
      E_entry.pack()
      Label(self.añadirentrada ,text="", bg = "slateGray").pack()
      Button(self.añadirentrada,text="Confirmar",font=('Times',10,), fg="black",width = "12", height = "1", bg = "LightSkyBlue3",command=lambda: self.entries.añadir(C_entry.get(),N_entry.get(),E_entry.get(),self.arbol)).pack()
      Label(self.añadirentrada,text="", bg="slateGray" ).pack()
      Button(self.añadirentrada,text="Salir",font=('Times', 10,), fg="black",width = "12", height = "1", bg = "LightSkyBlue3", command=self.añadirentrada.destroy).pack()

    def editarentrada(self):
        oldId=self.arbol.item(self.arbol.selection())['text']
        if oldId:
          #Vista de la ventana editar entrada
          self.editarentrada=Toplevel(self.ventana)
          self.editarentrada.geometry("400x415")
          self.editarentrada.title("Editar Entrada")
          self.editarentrada.config(bg="slategrey")
          self.editarentrada.resizable(0,0)
          self.editarentrada.iconbitmap("imagenes/Entradas.ico")
          codigo=IntVar(self.editarentrada)
          Nombre=StringVar(self.editarentrada)
          entradas=IntVar(self.editarentrada)
          fecha=StringVar(self.editarentrada)
          codigo.set(self.arbol.item(self.arbol.selection())["values"][0])
          Nombre.set(self.arbol.item(self.arbol.selection())["values"][1])
          entradas.set(self.arbol.item(self.arbol.selection())["values"][2])
          fecha.set(self.arbol.item(self.arbol.selection())["values"][3])
          Label(self.editarentrada ,text="", bg = "slateGray").pack()
          Label(self.editarentrada ,text="Por favor llenar las siguientes casillas para",font=('Times',10,), fg="black", bg = "slateGray").pack()
          Label(self.editarentrada ,text="editar una entrada", font=('Times',10,), fg="black", bg = "slateGray").pack()
          Label(self.editarentrada ,text="", bg = "slateGray").pack()
          Label(self.editarentrada ,text="Codigo del producto", font=('Times',10,), fg="black", width = "15", height = "1", bg = "slateGray").pack()
          id_entry = Entry(self.editarentrada, width = "40",textvariable=codigo)
          id_entry.pack()
          Label(self.editarentrada ,text="", bg = "slateGray").pack()
          Label(self.editarentrada ,text="Nombre", font=('Times',10,), fg="black", width = "12", height = "1", bg = "slateGray").pack()
          No_entry = Entry(self.editarentrada, width = "40", textvariable=Nombre)
          No_entry.pack()
          Label(self.editarentrada ,text="", bg = "slateGray").pack()
          Label(self.editarentrada ,text="Entradas", font=('Times',10,), fg="black", width = "12", height = "1", bg = "slateGray").pack()
          En_entry = Entry(self.editarentrada, width = "40", textvariable=entradas)
          En_entry.pack()
          Label(self.editarentrada ,text="", bg = "slateGray").pack()
          Label(self.editarentrada ,text="Fecha de entrada", font=('Times',10,), fg="black", width = "12", height = "1", bg = "slateGray").pack()
          Fe_entry = Entry(self.editarentrada, width = "40", textvariable=fecha)
          Fe_entry.pack()
          Label(self.editarentrada ,text="", bg = "slateGray").pack()
          Button(self.editarentrada,text="Confirmar",font=('Times',10,), fg="black",width = "12", height = "1", bg = "LightSkyBlue3",command=lambda:self.entries.editarEntrada(id_entry.get(),No_entry.get(),En_entry.get(),Fe_entry.get(),oldId,self.arbol)).pack()
          Label(self.editarentrada,text="", bg="slateGray" ).pack()
          Button(self.editarentrada,text="Salir",font=('Times', 10,), fg="black",width = "12", height = "1", bg = "LightSkyBlue3", command=self.editarentrada.destroy).pack()
        else:
          messagebox.showerror(message="Por favor elija una entrada para editar", title="mensaje")
          return